In [1]:
pip install numpy pandas matplotlib seaborn

Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
import numpy as np
print(dir(np))

['False_', 'ScalarType', 'True_', '_CopyMode', '_NoValue', '__NUMPY_SETUP__', '__all__', '__array_api_version__', '__array_namespace_info__', '__builtins__', '__cached__', '__config__', '__dir__', '__doc__', '__expired_attributes__', '__file__', '__former_attrs__', '__future_scalars__', '__getattr__', '__loader__', '__name__', '__numpy_submodules__', '__package__', '__path__', '__spec__', '__version__', '_array_api_info', '_core', '_distributor_init', '_expired_attrs_2_0', '_globals', '_int_extended_msg', '_mat', '_msg', '_pyinstaller_hooks_dir', '_pytesttester', '_specific_msg', '_type_info', '_typing', '_utils', 'abs', 'absolute', 'acos', 'acosh', 'add', 'all', 'allclose', 'amax', 'amin', 'angle', 'any', 'append', 'apply_along_axis', 'apply_over_axes', 'arange', 'arccos', 'arccosh', 'arcsin', 'arcsinh', 'arctan', 'arctan2', 'arctanh', 'argmax', 'argmin', 'argpartition', 'argsort', 'argwhere', 'around', 'array', 'array2string', 'array_equal', 'array_equiv', 'array_repr', 'array_split'

In [6]:
# numpy array operators
arr1 = np.array([1,2,3,4])
print(arr1)
print(np.ndim(arr1)) # it returned dimension of an array
print(np.size(arr1)) # it returns size of an array

[1 2 3 4]
1
4


In [11]:
# numpy array operators
arr1 = np.array([[1,2,3,4],[5,6,7,8]])
print(arr1)
print(np.ndim(arr1)) # it returned dimension of an array
print(np.size(arr1)) # it returns the size of an array
print(np.shape(arr1)) # it returns the rows and columns

[[1 2 3 4]
 [5 6 7 8]]
2
8
(2, 4)


In [14]:
arr1 = np.array([1,2,3,4])
arr2 = np.array([4,3,2,1])
print(arr1 + arr2)
print(arr1 - arr2)
print(np.shape(arr1), np.shape(arr2))
print(arr1 + 5)
print(arr1 * 2)

[5 5 5 5]
[-3 -1  1  3]
(4,) (4,)
[6 7 8 9]
[2 4 6 8]


In [19]:
# creating dataframe using pandas
import pandas as pd
df = pd.DataFrame([[1,2,3,4],[4,5,6,7]],columns = ['A', 'B','C','D'])
print(df)

   A  B  C  D
0  1  2  3  4
1  4  5  6  7


In [21]:
# creating dataframe using pandas
import pandas as pd
df = pd.DataFrame([["Akhil",12,13],['mahi',6,7],['srinu',15,10]],columns = ['Name', 'Age','Class'])
print(df)

    Name  Age  Class
0  Akhil   12     13
1   mahi    6      7
2  srinu   15     10


In [22]:
# access name column
df['Name']

0    Akhil
1     mahi
2    srinu
Name: Name, dtype: str

In [23]:
# access muliple column names
df[['Name','Age']]

,Name,Age
0,Akhil,12
1,mahi,6
2,srinu,15


In [29]:
# reading csv file
df =pd.read_csv(r"C:\Users\akhil\Desktop\python\python\Housing (1).csv")
df

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000,7420,4,2,3,yes,no,no,no,yes,2,yes,furnished
1,12250000,8960,4,4,4,yes,no,no,no,yes,3,no,furnished
2,12250000,9960,3,2,2,yes,no,yes,no,no,2,yes,semi-furnished
3,12215000,7500,4,2,2,yes,no,yes,no,yes,3,yes,furnished
4,11410000,7420,4,1,2,yes,yes,yes,no,yes,2,no,furnished
...,...,...,...,...,...,...,...,...,...,...,...,...,...
540,1820000,3000,2,1,1,yes,no,yes,no,no,2,no,unfurnished
541,1767150,2400,3,1,1,no,no,no,no,no,0,no,semi-furnished
542,1750000,3620,2,1,1,yes,no,no,no,no,0,no,unfurnished
543,1750000,2910,3,1,1,no,no,no,no,no,0,no,furnished


In [30]:
# find the dataframe informantion
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 545 entries, 0 to 544
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   price             545 non-null    int64
 1   area              545 non-null    int64
 2   bedrooms          545 non-null    int64
 3   bathrooms         545 non-null    int64
 4   stories           545 non-null    int64
 5   mainroad          545 non-null    str  
 6   guestroom         545 non-null    str  
 7   basement          545 non-null    str  
 8   hotwaterheating   545 non-null    str  
 9   airconditioning   545 non-null    str  
 10  parking           545 non-null    int64
 11  prefarea          545 non-null    str  
 12  furnishingstatus  545 non-null    str  
dtypes: int64(6), str(7)
memory usage: 55.5 KB


In [31]:
# get dataframe collums
df.columns


Index(['price', 'area', 'bedrooms', 'bathrooms', 'stories', 'mainroad',
       'guestroom', 'basement', 'hotwaterheating', 'airconditioning',
       'parking', 'prefarea', 'furnishingstatus'],
      dtype='str')

In [32]:
# find the numeical columns statical info
df.describe()

,price,area,bedrooms,bathrooms,stories,parking
count,5.450000e+02,545.000000,545.000000,545.000000,545.000000,545.000000
mean,4.766729e+06,5150.541284,2.965138,1.286239,1.805505,0.693578
std,1.870440e+06,2170.141023,0.738064,0.502470,0.867492,0.861586
min,1.750000e+06,1650.000000,1.000000,1.000000,1.000000,0.000000
25%,3.430000e+06,3600.000000,2.000000,1.000000,1.000000,0.000000
50%,4.340000e+06,4600.000000,3.000000,1.000000,2.000000,0.000000
75%,5.740000e+06,6360.000000,3.000000,2.000000,2.000000,1.000000
max,1.330000e+07,16200.000000,6.000000,4.000000,4.000000,3.000000


In [33]:
# find the categorical columns statical info
df.describe(include = 'str')

,mainroad,guestroom,basement,hotwaterheating,airconditioning,prefarea,furnishingstatus
count,545,545,545,545,545,545,545
unique,2,2,2,2,2,2,3
top,yes,no,no,no,no,no,semi-furnished
freq,468,448,354,520,373,417,227
